"""Add jlpt_level to Kanji model

Revision ID: b089fbce5664
Revises: 
Create Date: 2024-10-18 22:49:18.841007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b089fbce5664'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanji', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jlpt_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('radicals', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_kanji_learned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_learning_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_learning_method')
        batch_op.drop_column('total_kanji_learned')
        batch_op.drop_column('last_login')
        batch_op.drop_column('date_joined')

    with op.batch_alter_table('kanji', schema=None) as batch_op:
        batch_op.drop_column('radicals')
        batch_op.drop_column('jlpt_level')

    # ### end Alembic commands ###
